package com.tracker.workflow.model;

public enum WorkflowEvents {
    PLANNING_BUSINESS_SUBMIT,
    PLANNING_FINANCE_APPROVE,
    PLANNING_OWNER_SUBMIT,
    PLANNING_MANAGER_SUBMIT,
    TASK_DELEGATED,
    TASK_ESCALATED
}

/*
MANAGER_REJECT,
    HR_APPROVE,
    HR_REJECT,
    FINANCE_APPROVE,
    FINANCE_REJECT,
    CEO_APPROVE,
    CEO_REJECT,
    REWORK_TO_DRAFT,
    REWORK_TO_MANAGER,
    REWORK_TO_HR,
    COMPLETE
 */