package com.tracker.workflow.model;

public enum WorkflowStates {
    PENDING_PLANNING_BUSINESS_REVIEW,
    PENDING_PLANNING_FINANCE_APPROVAL,
    PENDING_PLANNING_OWNER_REVIEW,
    PENDING_PLANNING_MANAGER_REVIEW,
    COMPLETED
}

/*PENDING_EXECUTE_BUSINESS_REVIEW,
    PENDING_EXECUTE_MANAGER_APPROVAL,
    PENDING_EXECUTE_SPONSOR_APPROVAL,
    PENDING_SUSTAIN_BUSINESS_REVIEW,
    PENDING_SUSTAIN_OWNER_REVIEW,
    PENDING_SUSTAIN_MANAGER_REVIEW,
    REWORK_PLANNING_FINANCE,
    REWORK_PLANNING_MANAGER,
    REWORK_PLANNING_OWNER,

 */